on:
  workflow_call:
    inputs:
      folder:
        required: true
        type: string

jobs:
  test-report:
    runs-on: ubuntu-20.04

    services:
      postgres:
        image: postgres:11
        ports: ["5432:5432"]
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        env:
          POSTGRES_PASSWORD: postgres
    env:
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_HOST: localhost
      BUNDLE_GEMFILE: ${{ matrix.gemfile }}
      RUBY_VERSION: ${{ matrix.ruby }}

    strategy:
      matrix:
        gemfile:
          - gemfiles/decidim_0.26.gemfile
          - gemfiles/decidim_0.27.gemfile
        ruby:
          - 2.7.5
          - 3.0.2
        exclude:
          - gemfile: gemfiles/decidim_0.26.gemfile
            ruby: 3.0.2
          - gemfile: gemfiles/decidim_0.27.gemfile
            ruby: 2.7.5
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Setup Database
        run: bundle exec rake test_app

      - uses: nanasess/setup-chromedriver@v2
        with:
          chromedriver-version: 119.0.6045.105

      - uses: actions/setup-node@v3
        with:
          node-version: 18.17.1
          
      - run: mkdir -p ./spec/decidim_dummy_app/tmp/screenshots
        name: Create the screenshots folder
        shell: "bash"

      - name: Run RSpec
        run: bundle exec rspec ${{ inputs.folder }}
        env:
          SIMPLECOV: 1
          CODECOV: 1

      - uses: actions/upload-artifact@v2-preview
        if: always()
        with:
          name: screenshots
          path: ./spec/decidim_dummy_app/tmp/screenshots